In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([(1.6,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.6,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1.6, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c

array([[[1.6, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [10]:
np.arange(10,25,5)

array([10, 15, 20])

In [11]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [13]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.random.random((2,2))

array([[0.40861021, 0.4318637 ],
       [0.00191525, 0.109253  ]])

In [15]:
a.shape

(3,)

In [16]:
b.shape

(2, 3)

In [17]:
c.shape

(2, 2, 3)

In [18]:
a.ndim

1

In [19]:
b.ndim

2

In [20]:
c.ndim

3

In [21]:
a.size

3

In [22]:
b.size

6

In [23]:
c.size

12

In [24]:
a.dtype

dtype('int32')

In [25]:
b.dtype

dtype('float64')

In [26]:
c.dtype

dtype('float64')

In [27]:
a.dtype.name

'int32'

In [28]:
b.dtype.name

'float64'

In [29]:
c.dtype.name

'float64'

In [30]:
a.astype(int)

array([1, 2, 3])

In [31]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
c.astype(int)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [4, 5, 6]]])

In [33]:
np.add(a,b)

array([[2.6, 4. , 6. ],
       [5. , 7. , 9. ]])

In [34]:
np.subtract(a,b)

array([[-0.6,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [35]:
np.multiply(a,b)

array([[ 1.6,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [36]:
np.divide(a,b)

array([[0.625, 1.   , 1.   ],
       [0.25 , 0.4  , 0.5  ]])

In [37]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [38]:
np.sqrt(b)

array([[1.26491106, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [39]:
np.sqrt(c)

array([[[1.26491106, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [40]:
a.sum()

6

In [41]:
b.sum()

21.6

In [42]:
c.sum()

42.6

In [43]:
a.min()

1

In [44]:
b.min()

1.6

In [45]:
c.min()

1.0

In [46]:
a.max()

3

In [47]:
b.max()

6.0

In [48]:
c.max()

6.0

In [49]:
a.cumsum()

array([1, 3, 6])

In [50]:
b.cumsum()

array([ 1.6,  3.6,  6.6, 10.6, 15.6, 21.6])

In [51]:
c.cumsum()

array([ 1.6,  3.6,  6.6, 10.6, 15.6, 21.6, 24.6, 26.6, 27.6, 31.6, 36.6,
       42.6])

In [52]:
a.mean()

2.0

In [53]:
b.mean()

3.6

In [54]:
c.mean()

3.5500000000000003

In [55]:
np.median(a)

2.0

In [56]:
np.median(b)

3.5

In [57]:
np.median(c)

3.5

In [58]:
np.mod(a,b)

array([[1., 0., 0.],
       [1., 2., 3.]])

In [59]:
np.std(a)

0.816496580927726

In [60]:
np.std(b)

1.570562531918633

In [61]:
np.std(c)

1.6413916859380842